language: node_js
node_js:
- 5.7.0
sudo: required
services:
- docker
script:
- docker-compose -f docker-compose-test.yml build
- docker-compose -f docker-compose-test.yml run test
env:
  global:
  - secure: dRh9DcRCm/JmqSMJSpEYCkkOZ6qDttl1Y05cjKHosPE8SK3TFqFqZ3JaRL4dmzd1Q5DQSBpy1wF22XEjWSn5cAztW5t6Vl3+hh3wRKTByudoubnCe3Sgomw1cJqkkePGADUJICzqjoVSgimT8SJFavg2/IiNs376dB7ttu6nDzOIEduByMzQhYU9aPBFPt45dNF2o5wwy+oMHXqD8UHPhRh5N2r2Ey+WeaXwSgfqJDQkJzKz19pBtIPyR4jyEFikxCWT4C0O9QjjUEpEL8ZS8m9jqNyX5M0oLHNaAeBwbBtg/Ex+jPj3XHoGYsmxPsS7iJDt3QJOuSROvqclZdJvBxTttRLyEw55I/hq9/oA1zV9qGBUc+5EUYRJ3Tb8kvP/Rc5oFeVFJdZh1A+/+eA4JBOiNKQPRSLvNxDawaR4/4IGpbVh5MBOFqSTwX9+PqgBpILivMf9+F0hrbEInd6Hr6tmHRyNImZabP7T/CXDkfggrBnNIsHuXvWIgkv6tO2besTNTtOGGG8PNNwjJJ5c+64fHCfcfwQDppoIowq39rBwC+ZBCoAvrzZZs4TmFdLD3RVRuB/SSNp7cHjD57isg6YcMxV5PUMTL3DQOCwKPgTdLWf5Z4oejo1dUVcad7+Ag+sPMElrRjVPSzR14pgqbKYvhti4DAlJe5S1q2obsRA=
  - secure: FDPGv+qxrLuL0PD3m+Jg8Hyjo4pSF3zPOiOnnCJVcebgqqa6Wmn/O98Md67RpTUhI5ne9ZZ3VGzIZV9YrTV1cbKMdaDqDkkZNRUkGabyRq8VaA/0rm4b1mE5PPrEnVz843qbJD9Lkhm0+e5UM+Xcd/bBjOFZjLSUKg1CJ8wAFjtmoCMpJg6o3tImcmZ6yTermuaGz0HRJBqCJ1z07FiK6sDmEt6q5huXorNfg8pRhVAfmtUmOzuu4qBc+/LwXTrqD39DRNQzmkkiiRJddzq5sMMivS68PK/1lHk9tEfdP2Lmyu/Ob60iJ2w3Si+NaZLC3LJa43IqsqpzKikJ3K+DfGREaXIEQV5q1h+RHlNaVK6cgElxRXJ3QpMSCTZZ1rvhvtNZDWmiKBLjYsG0bCEbPjh+zPIuGW3UJniuSMUSFrvP8FCZjSeVbYFzieSg6hHKgAk8phSjKB9q0ii6rFUZQIMqHxvj/tnMryWg0MNbVTRSWcgDeBvlIkuoBbXDCFFpewWW1PlTL+G72N998910JFIG0R5ORoID4DKfaToMEzmMfVan511UjJ0t4WdvhIEBtaTjT92uUuH8jpI4KmigYKRfiZIojFJzoxs3J73AKG8PP3b7Qs+bSk4DWuav9ZAodOzCfkraBviy1yWc3xF9715aapvthdkdLOWZDlLZfEE=
before_install:
- bash _scripts/install.sh
after_success:
- bash _scripts/deploy.sh
