language: node_js
node_js:
- 5.7.0
sudo: required
services:
- docker
script:
- docker-compose -f docker-compose-test.yml build
- docker-compose -f docker-compose-test.yml run test
deploy:
  provider: heroku
  app: gfw-ogr-api-staging
  api_key:
    secure: AFTqPlDp3lWDX7rm3nK5scyCAZBmCC03YUDFGyLEyf4cXdelequ28X/Encss3XAOiIx0FyTxgo7UWIiYMVY9PFrKPy6iSognBbEvQ+LSMfFZuYCGcN+0I6b5gbBCFZaLQFgCLQ0IWr00M8PhQdtvdbEpusUOuFSzzPkXduTYDwhHoSIyi4tQlamVMDxwKTXdDLFACMMfRa7vcTPLobX+snOmqYl+sZiwUotyZpChVvfij231wb26wH5PcbNmU9uLtBnmxknbEEkcsGGLuIG1h7jrUL03dyUZq6uHRMTN7C6l3kb2YpXlm8i+x2jVmOyu+U+jn6rvoDXpHJBOUnt4dVz4mh/zrRNxF5OOH71Mzzd597zjqcee0aq3xBH/eDr/UG7t6nxsu56TQfvszjLIRjq1agW/TZ86k+XIb+DYnCP35DCwEoWgzpDHxyUYhde5sixa3XKBvFOCXz1UPUG1kfduVDYsPc8+Cylv39SZmizyba12oLBUj1cf3fUrPNavM4VW4bKeQPzmzYFN43LZTPz4rKpHULomiiDFJ1bhGK7zzGQK2SL+lbbGBp9I44HqvD7/15tUTc8sLV4qod1aaIvuwmtOZC2sOhzK+FSRje02ocdBLvZf2yayGptz70d020vAtL2ir30Aqmmq00GUTd+w6uNYQs2R8GQZvpovC8k=
env:
  global:
  - secure: dXl7FiGj2uUpii0BdkcCP30TVxT1HfLVWQCx7LqZrcR/zzcIfmgm1dpdUwSpiHwTa2e9k2pOo6Lo3DnX19lmO7wvHofiSxDq+oNqt/hVMQWbE8S0eZHH7BVqDkGqDFZ5XUmER8L3bXI4JrahMMCpUoN1Rk8m1StltAW3Vrc/mMYsiMYb/8f6GPQWLblTcsdY+UX6IgUZDiRA/UnFHClmw5f61i89bsFQ2Bbhd/g1gvz8DDKQHhep381JqCEdgJcn+xhzshZ8x4iydRopIaDHctFwFB19L7I8Hb5kduXYZcKOzp407Qc09DikHXMkJLjG3MG5/ivgMz7v0cTBJRoOOu/BE5PX0srT/e2VuUR6HLoCng821kukezlrzwXGwYx0oivzGQ/KwK5CEZpMpxKel+UDGdQI1pA/EEcCeJ+tSaMW0fjslxj3LaU8tiXns1QQZsQkhuF339dn/A4Dxu3llrHr5zHsX2Yje3XyeEIJpkV8/gLrNP5Lt3giYsQJfHFmsqPWVSF7q/30Potp8AI9QcjJPiKykL3sdX/Kg+jepDMERKhDDCTeJiZmHFYEscpN6G+C+SiGl8hPNIbblCPka/XLbC8wvKWep3gJja9VrBz11EccHGVY1xusBkfQ8XCzj8LigN8a7TYIn/MeMTHz/mcmQDxCVA8n/+FGCIRaR/Y=
  - secure: EMoRfqmOoh6DIYHdDTbxxlntUBFjbniph9DZ97SBPbBVzN/zdzEFS4WCYuQGjL8J5pfTqmpcvqSxUdYL2M9krqXx3rERnxSOF3FNHee0j2AR5PW2GulH7Ybw2By8zWQlfGm43Z9cWXdV2//YCe+QDd4EFe7wbm8JSZM/1xY1CTw5r9ZWX0AqOlyC0CdgzulG2dhmUU95ht6rFk5/RhM9XL+7Ev2wtLCLkocOy9+piVHMBrjzvm89aqomYVx480cy2uHnnLJoVPhXwmvVFyH0BuXa24sPOtOSwZQ5Gooe4F7dMkDrgUQxwpt3C2QhP0p8WvJv9CykEDGc5N+yCsRdS7t7pJUL0nZvXqP6NO2QaHaKfqGYc4V2QxAoRNjcdiw3gXtn+XXy82cEVk5imwme7Jecu18xqtVM04cuivdqqPqyiXc13Xfq381uDkdjndYTDNUsMDykUgnsy4BTdg+STDShj5kkpFvFX6ZKBMDBH16EHcnIg8PaW8UJIVmRlMvAlT/78t+F0s0ZYv+h5Pxu1XZyh8hXVnFtaATL0w5s4HUzJHqUYU0gzVaLuuaFGGeprVzhNkc9RAQT3n0sbVszlE1mHyeJy8daT/qrskSAzR3pi6Rfh5kHCsT0Dn2X3JDONDjonbKsvKMJyQQ3gd5ySNYcFIdd8/a0tQxDyOMKpKg=
before_install:
- openssl aes-256-cbc -K $encrypted_da3b25071652_key -iv $encrypted_da3b25071652_iv
  -in deploy-key.enc -out deploy-key -d
