version: "3"
services:
  test:
    build: .
    ports:
        - "3200"
    container_name: gfw-ogr-api-test
    environment:
      CT_URL: http://mymachine:9000
      API_VERSION: v1
      CT_REGISTER_MODE: auto
      NODE_ENV: test
      PORT: 3200
      USER: root
      NODE_PATH: app/src
    command: test
