prod:
  image: vizzuality/gfw-ogr-api:1.0.1${STAGING}
  ports:
    - "3200"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "gelf"
  log_opt:
    gelf-address: ${GELF_ADDRESS}
