prod:
  image: vizzuality/gfw-ogr-api:1.0.1${STAGING}
  cpu_shares: 73
  cpu_quota: 50000
  cpuset: 0,5
  ports:
    - "3200"
  env_file:
    - prod.env
  command: start
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: gfw-ogr-api${STAGING}
