develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35730:35729"
  container_name: gfw-ogr-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URI: http://192.168.99.100:8000
    SELF_REGISTRY: "off"
  command: develop
  volumes:
    - ./app:/opt/gfw-ogr-api/app
