develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35730:35729"
  container_name: gfw-ogr-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URL: http://mymachine:9000
    CT_REGISTER_MODE: auto
  command: develop
  volumes:
    - ./app:/opt/gfw-ogr-api/app
