develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35730:35729"
  container_name: gfw-ogr-api-develop
  environment:
    NODE_ENV: dev
    API_GATEWAY_URL: http://mymachine:9000
    CT_REGISTER_MODE: auto
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:3200
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
  command: develop
  volumes:
    - ./app:/opt/gfw-ogr-api/app
  extra_hosts:
    - "mymachine:$MYMACHINE"
