apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gfw
  labels:
    name: gfw-ogr
  name: gfw-ogr
spec:
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        name: gfw-ogr
    spec:
      containers:
      - name: gfw-ogr
        image: vizzuality/gfw-ogr
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "3200"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://gfw-ogr.gfw.svc.cluster.local:3200
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 3200
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3200
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 3200
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
