apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: gfw-ogr
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: gfw-ogr
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
